# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#   
#     Referêcnias:
#     https://github.com/joaopedropio/zmk-swoop/blob/main/config/boards/shields/swoop/central_dongle.overlay
#     https://github.com/aroum/zmk-enki42-dongle/tree/N!N_v2?tab=readme-ov-file
#     https://github.com/BertPlasschaert/zmk-config-totem-dongle/tree/main
#     https://github.com/BertPlasschaert/zmk-config-totem-dongle
#     https://www.youtube.com/watch?v=O_urj-rF3bQ&t=447s
---
include:
  - board: seeeduino_xiao_ble
    shield: skb50_left
  - board: seeeduino_xiao_ble
    shield: skb50_right
  - board: seeeduino_xiao_ble
    shield: skb50_numpad
    artifact-name: numpad_firmware
  - board: seeeduino_xiao_ble
    shield: central_dongle
    cmake-args: -DCONFIG_ZMK_DONGLE=y
    artifact-name: dongle_firmware
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings_reset_firmware
